name: secure_dotenv_generator
description: Code generator for secure_dotenv
version: 0.3.0
homepage: https://github.com/tomassasovsky/secure_dotenv.dart.git
repository: https://github.com/tomassasovsky/secure_dotenv.dart.git

environment:
  sdk: ">=2.17.3 <4.0.0"

dependencies:
  analyzer: ^6.0.0
  build: ^2.4.1
  collection: ^1.17.2
  dotenv: ^4.1.0
  secure_dotenv: ^0.3.0
  encrypt: ^5.0.1
  source_gen: ^1.4.0
  source_helper: ^1.3.4
  logging: ^1.2.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.2
