name: secure_dotenv_generator
description: Code generator for secure_dotenv
version: 1.0.0
homepage: https://github.com/tomassasovsky/secure_dotenv.dart.git
repository: https://github.com/tomassasovsky/secure_dotenv.dart.git

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  analyzer: ^6.41.0
  build: ^2.4.0
  collection: ^1.17.2
  dotenv: ^4.1.0
  secure_dotenv: ^1.0.0
  pointycastle: ^3.7.3
  source_gen: ^1.3.2
  source_helper: ^1.3.3
  logging: ^1.2.0

dev_dependencies:
  build_runner: ^2.4.5
  flutter_lints: ^2.0.1
