name: secure_dotenv
description: Generate encrypted environment variable dart files from an `.env` file.
version: 0.4.0
homepage: https://github.com/tomassasovsky/secure_dotenv.dart.git
repository: https://github.com/tomassasovsky/secure_dotenv.dart.git

environment:
  sdk: ">=2.17.3 <4.0.0"

dev_dependencies:
  flutter_lints: ^2.0.2

dependencies:
  crypto_x: ^0.0.3+2
